perf: Fix building error in x86_64
ld with ARCH=x86_64, perf failed to compile with following error:

tests/builtin-test.o:(.data+0x158): undefined reference to `test__perf_time_to_tsc'
collect2: error: ld returned 1 exit status
Makefile.perf:632: recipe for target 'perf' failed
...

Which is caused commit c6e5e9fbc3ea1 ("perf tools: Fix building error
in x86_64 when dwarf unwind is on"), ARCH test in Makefile.perf
conflicts with tests/builtin-test.c's __x86_64__.
To x86/x86_64 platform, ARCH should always override to x86 while
IS_64_BIT stands for the actual architecture.

Change-Id: I0d6f193756945d854419c2fdfb5e1ba2dda3e180
True-Author: He Kuang <hekuang@xxxxxxxxxx>
Signed-off-by: He Kuang <hekuang@xxxxxxxxxx>
Signed-off-by: José Bollo <jose.bollo@open.eurogiciel.org>